version: '3.7'
services:
    nginx:
      image: nginx:latest
      ports:
      - target: 80
        published: 80
      volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
      depends_on:
      - client
      - server
    client:    
      image: localhost:5000/static_website_image:latest
      build:
        context: ./static_website
    server:
      image: localhost:5000/server_image:latest
      build:
        context: ./server
    mongo:
      image: mongo:latest
      ports:
      - "27017:27017"
    numgen:
      image: localhost:5000/numgen:6fig
    texgen:
      image: localhost:5000/texgen:2char
    prizegen:
      image: localhost:5000/prize:highprize
    db_connector:
      image: localhost:5000/db_connector_image
      depends_on: 
      - mongo
      ports:
      - "5001:5001"
    
